import os


DEFAULT_REDIS_URL = "redis://localhost:6379/0"
DEFAULT_SEARCH_CACHE_TTL_SECONDS = 900
DEFAULT_REDIS_CONNECT_TIMEOUT_SECONDS = 0.5
DEFAULT_REDIS_SOCKET_TIMEOUT_SECONDS = 0.5


REDIS_URL = os.getenv(
    "REDIS_URL",
    DEFAULT_REDIS_URL,
)

SEARCH_CACHE_TTL_SECONDS = int(
    os.getenv(
        "SEARCH_CACHE_TTL_SECONDS",
        str(DEFAULT_SEARCH_CACHE_TTL_SECONDS),
    )
)

REDIS_CONNECT_TIMEOUT_SECONDS = float(
    os.getenv(
        "REDIS_CONNECT_TIMEOUT_SECONDS",
        str(DEFAULT_REDIS_CONNECT_TIMEOUT_SECONDS),
    )
)

REDIS_SOCKET_TIMEOUT_SECONDS = float(
    os.getenv(
        "REDIS_SOCKET_TIMEOUT_SECONDS",
        str(DEFAULT_REDIS_SOCKET_TIMEOUT_SECONDS),
    )
)