"""create repositories table

Revision ID: 4009108aa0ea
Revises: 
Create Date: 2026-07-13 21:23:16.956593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4009108aa0ea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repositories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('canonical_path', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'indexing'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('index_version', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('indexing', 'ready', 'failed')", name='ck_repositories_status'),
    sa.CheckConstraint('index_version >= 0', name='ck_repositories_index_version_nonnegative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_path')
    )
    op.create_index('uq_repositories_single_active', 'repositories', ['is_active'], unique=True, postgresql_where=sa.text('is_active'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_repositories_single_active', table_name='repositories', postgresql_where=sa.text('is_active'))
    op.drop_table('repositories')
    # ### end Alembic commands ###
