"""create indexing runs table

Revision ID: 6cec963c0c30
Revises: 904c13f0853e
Create Date: 2026-07-13 22:14:21.529480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cec963c0c30'
down_revision: Union[str, Sequence[str], None] = '904c13f0853e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indexing_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'running'"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('files_discovered', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('files_indexed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('files_updated', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('files_deleted', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('running', 'succeeded', 'failed')", name='ck_indexing_runs_status'),
    sa.CheckConstraint('files_deleted >= 0', name='ck_indexing_runs_files_deleted_nonnegative'),
    sa.CheckConstraint('files_discovered >= 0', name='ck_indexing_runs_files_discovered_nonnegative'),
    sa.CheckConstraint('files_indexed >= 0', name='ck_indexing_runs_files_indexed_nonnegative'),
    sa.CheckConstraint('files_updated >= 0', name='ck_indexing_runs_files_updated_nonnegative'),
    sa.CheckConstraint('total_tokens >= 0', name='ck_indexing_runs_total_tokens_nonnegative'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indexing_runs_repository_id'), 'indexing_runs', ['repository_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_indexing_runs_repository_id'), table_name='indexing_runs')
    op.drop_table('indexing_runs')
    # ### end Alembic commands ###
